/** Typed asset manifest — maps logical IDs to local image paths */

const B = import.meta.env.BASE_URL;

export const TAB_ICONS = {
  combat: `${B}images/tabs/Combat_icon.png`,
  stats: `${B}images/tabs/Skills_icon.png`,
  quests: `${B}images/tabs/Quest_List_tab_icon.png`,
  equipment: `${B}images/tabs/Worn_Equipment.png`,
  prayer: `${B}images/tabs/Prayer_tab_icon.png`,
  spellbook: `${B}images/tabs/Spellbook.png`,
  clan: `${B}images/tabs/Your_Clan_icon.png`,
  friends: `${B}images/tabs/Friends_List.png`,
  ignore: `${B}images/tabs/Ignore_List.png`,
  logout: `${B}images/tabs/Logout.png`,
  settings: `${B}images/tabs/Settings.png`,
  emotes: `${B}images/tabs/Emotes_button.png`,
  music: `${B}images/tabs/Music.png`,
  inventory: `${B}images/tabs/Inventory.png`,
} as const;

export const ITEM_SPRITES = {
  paddlefish: `${B}images/items/Paddlefish.png`,
  corrupted_paddlefish: `${B}images/items/Corrupted_paddlefish.png`,
  egniol_1: `${B}images/items/Egniol_potion_(1).png`,
  egniol_2: `${B}images/items/Egniol_potion_(2).png`,
  egniol_3: `${B}images/items/Egniol_potion_(3).png`,
  egniol_4: `${B}images/items/Egniol_potion_(4).png`,
  bow_1: `${B}images/items/Corrupted_bow_(basic).png`,
  bow_2: `${B}images/items/Corrupted_bow_(attuned).png`,
  bow_3: `${B}images/items/Corrupted_bow_(perfected).png`,
  staff_1: `${B}images/items/Corrupted_staff_(basic).png`,
  staff_2: `${B}images/items/Corrupted_staff_(attuned).png`,
  staff_3: `${B}images/items/Corrupted_staff_(perfected).png`,
  halberd_1: `${B}images/items/Corrupted_halberd_(basic).png`,
  halberd_2: `${B}images/items/Corrupted_halberd_(attuned).png`,
  halberd_3: `${B}images/items/Corrupted_halberd_(perfected).png`,
  helm_1: `${B}images/items/Corrupted_helm_(basic).png`,
  helm_2: `${B}images/items/Corrupted_helm_(attuned).png`,
  helm_3: `${B}images/items/Corrupted_helm_(perfected).png`,
  body_1: `${B}images/items/Corrupted_body_(basic).png`,
  body_2: `${B}images/items/Corrupted_body_(attuned).png`,
  body_3: `${B}images/items/Corrupted_body_(perfected).png`,
  legs_1: `${B}images/items/Corrupted_legs_(basic).png`,
  legs_2: `${B}images/items/Corrupted_legs_(attuned).png`,
  legs_3: `${B}images/items/Corrupted_legs_(perfected).png`,
} as const;

export const PRAYER_ICONS: Record<string, string> = {
  thick_skin: `${B}images/prayers/Thick_Skin.png`,
  burst_of_strength: `${B}images/prayers/Burst_of_Strength.png`,
  clarity_of_thought: `${B}images/prayers/Clarity_of_Thought.png`,
  sharp_eye: `${B}images/prayers/Sharp_Eye.png`,
  mystic_will: `${B}images/prayers/Mystic_Will.png`,
  rock_skin: `${B}images/prayers/Rock_Skin.png`,
  superhuman_str: `${B}images/prayers/Superhuman_Strength.png`,
  improved_reflexes: `${B}images/prayers/Improved_Reflexes.png`,
  rapid_restore: `${B}images/prayers/Rapid_Restore.png`,
  rapid_heal: `${B}images/prayers/Rapid_Heal.png`,
  protect_item: `${B}images/prayers/Protect_Item.png`,
  hawk_eye: `${B}images/prayers/Hawk_Eye.png`,
  mystic_lore: `${B}images/prayers/Mystic_Lore.png`,
  steel_skin: `${B}images/prayers/Steel_Skin.png`,
  ultimate_str: `${B}images/prayers/Ultimate_Strength.png`,
  incredible_reflexes: `${B}images/prayers/Incredible_Reflexes.png`,
  protect_from_magic: `${B}images/prayers/Protect_from_Magic.png`,
  protect_from_missiles: `${B}images/prayers/Protect_from_Missiles.png`,
  protect_from_melee: `${B}images/prayers/Protect_from_Melee.png`,
  eagle_eye: `${B}images/prayers/Eagle_Eye.png`,
  mystic_might: `${B}images/prayers/Mystic_Might.png`,
  retribution: `${B}images/prayers/Retribution.png`,
  redemption: `${B}images/prayers/Redemption.png`,
  smite: `${B}images/prayers/Smite.png`,
  preserve: `${B}images/prayers/Preserve.png`,
  chivalry: `${B}images/prayers/Chivalry.png`,
  piety: `${B}images/prayers/Piety.png`,
  rigour: `${B}images/prayers/Rigour.png`,
  augury: `${B}images/prayers/Augury.png`,
} as const;

export const OVERHEAD_ICONS = {
  magic: `${B}images/overheads/Protect_from_Magic_overhead.png`,
  missiles: `${B}images/overheads/Protect_from_Missiles_overhead.png`,
  melee: `${B}images/overheads/Protect_from_Melee_overhead.png`,
} as const;
