/** Typed asset manifest — maps logical IDs to local image paths */

export const TAB_ICONS = {
  combat: '/images/tabs/Combat_icon.png',
  stats: '/images/tabs/Skills_icon.png',
  quests: '/images/tabs/Quest_List_tab_icon.png',
  equipment: '/images/tabs/Worn_Equipment.png',
  prayer: '/images/tabs/Prayer_tab_icon.png',
  spellbook: '/images/tabs/Spellbook.png',
  clan: '/images/tabs/Your_Clan_icon.png',
  friends: '/images/tabs/Friends_List.png',
  ignore: '/images/tabs/Ignore_List.png',
  logout: '/images/tabs/Logout.png',
  settings: '/images/tabs/Settings.png',
  emotes: '/images/tabs/Emotes_button.png',
  music: '/images/tabs/Music.png',
  inventory: '/images/tabs/Inventory.png',
} as const;

export const ITEM_SPRITES = {
  paddlefish: '/images/items/Paddlefish.png',
  corrupted_paddlefish: '/images/items/Corrupted_paddlefish.png',
  egniol_1: '/images/items/Egniol_potion_(1).png',
  egniol_2: '/images/items/Egniol_potion_(2).png',
  egniol_3: '/images/items/Egniol_potion_(3).png',
  egniol_4: '/images/items/Egniol_potion_(4).png',
  bow_1: '/images/items/Corrupted_bow_(basic).png',
  bow_2: '/images/items/Corrupted_bow_(attuned).png',
  bow_3: '/images/items/Corrupted_bow_(perfected).png',
  staff_1: '/images/items/Corrupted_staff_(basic).png',
  staff_2: '/images/items/Corrupted_staff_(attuned).png',
  staff_3: '/images/items/Corrupted_staff_(perfected).png',
  halberd_1: '/images/items/Corrupted_halberd_(basic).png',
  halberd_2: '/images/items/Corrupted_halberd_(attuned).png',
  halberd_3: '/images/items/Corrupted_halberd_(perfected).png',
  helm_1: '/images/items/Corrupted_helm_(basic).png',
  helm_2: '/images/items/Corrupted_helm_(attuned).png',
  helm_3: '/images/items/Corrupted_helm_(perfected).png',
  body_1: '/images/items/Corrupted_body_(basic).png',
  body_2: '/images/items/Corrupted_body_(attuned).png',
  body_3: '/images/items/Corrupted_body_(perfected).png',
  legs_1: '/images/items/Corrupted_legs_(basic).png',
  legs_2: '/images/items/Corrupted_legs_(attuned).png',
  legs_3: '/images/items/Corrupted_legs_(perfected).png',
} as const;

export const PRAYER_ICONS: Record<string, string> = {
  thick_skin: '/images/prayers/Thick_Skin.png',
  burst_of_strength: '/images/prayers/Burst_of_Strength.png',
  clarity_of_thought: '/images/prayers/Clarity_of_Thought.png',
  sharp_eye: '/images/prayers/Sharp_Eye.png',
  mystic_will: '/images/prayers/Mystic_Will.png',
  rock_skin: '/images/prayers/Rock_Skin.png',
  superhuman_str: '/images/prayers/Superhuman_Strength.png',
  improved_reflexes: '/images/prayers/Improved_Reflexes.png',
  rapid_restore: '/images/prayers/Rapid_Restore.png',
  rapid_heal: '/images/prayers/Rapid_Heal.png',
  protect_item: '/images/prayers/Protect_Item.png',
  hawk_eye: '/images/prayers/Hawk_Eye.png',
  mystic_lore: '/images/prayers/Mystic_Lore.png',
  steel_skin: '/images/prayers/Steel_Skin.png',
  ultimate_str: '/images/prayers/Ultimate_Strength.png',
  incredible_reflexes: '/images/prayers/Incredible_Reflexes.png',
  protect_from_magic: '/images/prayers/Protect_from_Magic.png',
  protect_from_missiles: '/images/prayers/Protect_from_Missiles.png',
  protect_from_melee: '/images/prayers/Protect_from_Melee.png',
  eagle_eye: '/images/prayers/Eagle_Eye.png',
  mystic_might: '/images/prayers/Mystic_Might.png',
  retribution: '/images/prayers/Retribution.png',
  redemption: '/images/prayers/Redemption.png',
  smite: '/images/prayers/Smite.png',
  preserve: '/images/prayers/Preserve.png',
  chivalry: '/images/prayers/Chivalry.png',
  piety: '/images/prayers/Piety.png',
  rigour: '/images/prayers/Rigour.png',
  augury: '/images/prayers/Augury.png',
} as const;

export const OVERHEAD_ICONS = {
  magic: '/images/overheads/Protect_from_Magic_overhead.png',
  missiles: '/images/overheads/Protect_from_Missiles_overhead.png',
  melee: '/images/overheads/Protect_from_Melee_overhead.png',
} as const;
